name: release shape-shifter
on: push

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: | 
            echo "$(cat VERSION.md)-beta"
          prerelease: true
          title: "Development Build"
