name: Clojure tests

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run lint
      run: clojure -M:clojure-lsp format --dry

    - name: Run tests
      run: clojure -M:test
